### ISSUE TITLE
Weird display issues?

### ISSUE THREAD

**Issue by masonticehurst** [JustPlayerDE/LuaCheck#2]
Hey there, thought I'd give this a shot since it seems quite useful!

I've attempted to put a copy on my XAMPP server (direct clone from master branch on GitHub) and I only seem to get parts of the PHP code embedded into the page.

Example:
![](https://i.gyazo.com/a1f7eae41f58a30f652d200e3f74d29e.png)

Am I doing something wrong or am I missing a dependency?

**Comment by masonticehurst** [comment]
Whoops, I just noticed you had an online version already. Seems to work great

**Comment by justinkluever** [comment]
oh thanks for notice me that i have forgot to change the short php tag (<?) to the normaö tag (<?php) 
i cant change it right now but for now it can be fixed if you enable short tags in the php.ini or change the tags ^^

(no computer right now)

**Comment by justinkluever** [comment]
its fixed now :)
