### ISSUE TITLE
Website issue

### ISSUE THREAD

**Issue by ellwoodops** [JustPlayerDE/LuaCheck#3]
I inserted all your files onto a webhost and when i click submit after selecting a file i get this error
`Parse error: syntax error, unexpected end of file in /storage/ssd4/400/2585400/public_html/include/check.php on line 104`

**Comment by justinkluever** [comment]
i just pushed an updated version where you can edit it more easier (but the problem may not be solved) 
can you name your host? because on my host it still works ( https://trash.justplayer.de/luacheck )

**Comment by ellwoodops** [comment]
I use 000webhost and i am uploading the updated files and will let you know how it works.

**Comment by justinkluever** [comment]
because my tests are all negative about this issue and because you dont give an update i close this for now
